### PR TITLE
fix: restrict proxy paths that can be forwarded to cloud-api

### LINKED ISSUE #23: Potential Security Risk: Unrestricted URL Forwarding
Currently, chat-api forwards requests without imposing restrictions on the target URLs. This behavior could lead to unintended misuse of the configured cloud-api API key. Specifically, if a user or external actor forwards requests to arbitrary endpoints, the API key could be exposed or used in ways not intended by the system.

### PR DESCRIPTION
**Pull request by hanakannzashi**
Fixes #23

### CODE REVIEW

File: crates/api/src/consts.rs [hunk 1]
```diff
@@ -1,2 +1,5 @@
 pub const SYSTEM_PROMPT_MAX_LEN: usize = 64 * 1024;
 pub const LIMIT_MAX: i64 = 100;
+
+/// Allowed proxy paths that can be forwarded to OpenAI
+pub const ALLOWED_PROXY_PATHS: &[&str] = &["responses", "chat/completions", "models"];
```
Comment (think-in-universe) [inline crates/api/src/consts.rs]: Let's carefully review the endpoints that we'd like to whitelist. I think we're missing below endpoints:

- `/model`: e.g. `/model/list`
- `/conversations`
- `/files`
- `/signature`

**Review by think-in-universe — CHANGES_REQUESTED** [review]
